name: cafegestor
description: Cafe Gestor 60L
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  mobile_scanner: ^3.5.6
  pdf: ^3.10.4
  printing: ^5.10.4
  intl: ^0.18.1
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  qr_flutter: ^4.0.0

flutter:
  uses-material-design: true
